// CSVデータの型定義
interface CsvData {
  id: number; // ID
  checked: boolean; // 選択
  loadingResult: string; // 読み込み結果
  tournId: string; // 大会ID
  tournIdError: boolean; // 大会IDエラーの有無
  entrysystemTournId: string; // エントリーシステム大会ID
  entrysystemTournIdError: boolean; // エントリーシステム大会IDエラーの有無
  tournName: string; // 大会名
  tournNameError: boolean; // 大会名エラーの有無
  userId: string; // 選手ID
  userIdError: boolean; // 選手IDエラーの有無
  jaraPlayerId: string; // JARA選手コード
  jaraPlayerIdError: boolean; // JARA選手コードエラーの有無
  playerName: string; // 選手名
  playerNameError: boolean; // 選手名エラーの有無
  raceId: string; // レースID
  raceIdError: boolean; // レースIDエラーの有無
  entrysystemRaceId: string; // エントリーシステムレースID
  entrysystemRaceIdError: boolean; // エントリーシステムレースIDエラーの有無
  raceNumber: string; // レースNo
  raceNumberError: boolean; // レースNoエラーの有無
  raceName: string; // レース名
  raceNameError: boolean; // レース名エラーの有無
  raceTypeId: string; // レース区分ID
  raceTypeIdError: boolean; // レース区分IDエラーの有無
  raceTypeName: string; // レース区分名
  raceTypeNameError: boolean; // レース区分名エラーの有無
  orgId: string; // 団体ID
  orgIdError: boolean; // 団体IDエラーの有無
  entrysystemOrgId: string; // エントリーシステム団体ID
  entrysystemOrgIdError: boolean; // エントリーシステム団体IDエラーの有無
  orgName: string; // 団体名
  orgNameError: boolean; // 団体名エラーの有無
  crewName: string; // クルー名
  crewNameError: boolean; // クルー名エラーの有無
  byGroup: string; // 組別
  byGroupError: boolean; // 組別エラーの有無
  eventId: string; // 種目ID
  eventIdError: boolean; // 種目IDエラーの有無
  eventName: string; // 種目名
  eventNameError: boolean; // 種目名エラーの有無
  range: string; // 距離
  rangeError: boolean; // 距離エラーの有無
  rank: string; // 順位
  rankError: boolean; // 順位エラーの有無
  fiveHundredmLaptime: string; // 500mラップタイム
  fiveHundredmLaptimeError: boolean; // 500mラップタイムエラーの有無
  tenHundredmLaptime: string; // 1000mラップタイム
  tenHundredmLaptimeError: boolean; // 1000mラップタイムエラーの有無
  fifteenHundredmLaptime: string; // 1500mラップタイム
  fifteenHundredmLaptimeError: boolean; // 1500mラップタイムエラーの有無
  twentyHundredmLaptime: string; // 2000mラップタイム
  twentyHundredmLaptimeError: boolean; // 2000mラップタイムエラーの有無
  finalTime: string; // 最終タイム
  finalTimeError: boolean; // 最終タイムエラーの有無
  strokeRateAvg: string; // ストロークレート（平均）
  strokeRateAvgError: boolean; // ストロークレート（平均）エラーの有無
  fiveHundredmStrokeRat: string; // 500mストロークレート
  fiveHundredmStrokeRatError: boolean; // 500mストロークレートエラーの有無
  tenHundredmStrokeRat: string; // 1000mストロークレート
  tenHundredmStrokeRatError: boolean; // 1000mストロークレートエラーの有無
  fifteenHundredmStrokeRat: string; // 1500mストロークレート
  fifteenHundredmStrokeRatError: boolean; // 1500mストロークレートエラーの有無
  twentyHundredmStrokeRat: string; // 2000mストロークレート
  twentyHundredmStrokeRatError: boolean; // 2000mストロークレートエラーの有無
  heartRateAvg: string; // 平均心拍数
  heartRateAvgError: boolean; // 平均心拍数エラーの有無
  fiveHundredmHeartRate: string; // 500m心拍数
  fiveHundredmHeartRateError: boolean; // 500m心拍数エラーの有無
  tenHundredmHeartRate: string; // 1000m心拍数
  tenHundredmHeartRateError: boolean; // 1000m心拍数エラーの有無
  fifteenHundredmHeartRate: string; // 1500m心拍数
  fifteenHundredmHeartRateError: boolean; // 1500m心拍数エラーの有無
  twentyHundredmHeartRate: string; // 2000m心拍数
  twentyHundredmHeartRateError: boolean; // 2000m心拍数エラーの有無
  official: string; // 公式/非公式
  officialError: boolean; // 公式/非公式エラーの有無
  attendance: string; // 立ち合い有無
  attendanceError: boolean; // 立ち合い有無エラーの有無
  ergoWeight: string; // エルゴ重量
  ergoWeightError: boolean; // エルゴ重量エラーの有無
  playerHeight: string; // 選手身長
  playerHeightError: boolean; // 選手身長エラーの有無
  playerWeight: string; // 選手体重
  playerWeightError: boolean; // 選手体重エラーの有無
  mSheetNumber: string; // シート番号ID
  mSheetNumberError: boolean; // シート番号IDエラーの有無
  sheetName: string; // シート番号
  sheetNameError: boolean; // シート番号エラーの有無
  raceResultRecordName: string; // 出漕結果記録名
  raceResultRecordNameError: boolean; // 出漕結果記録名エラーの有無
  startDatetime: string; // 発艇日時
  startDatetimeError: boolean; // 発艇日時エラーの有無
  weather: string; // 天候
  weatherError: boolean; // 天候エラーの有無
  windSpeedTwentyHundredmPoint: string; // 2000m地点風速
  windSpeedTwentyHundredmPointError: boolean; // 2000m地点風速エラーの有無
  windDirectionTwentyHundredmPoint: string; // 2000m地点風向
  windDirectionTwentyHundredmPointError: boolean; // 2000m地点風向エラーの有無
  windSpeedTenHundredmPoint: string; // 1000m地点風速
  windSpeedTenHundredmPointError: boolean; // 1000m地点風速エラーの有無
  windDirectionTenHundredmPoint: string; // 1000m地点風向
  windDirectionTenHundredmPointError: boolean; // 1000m地点風向エラーの有無
  remark: string; // 備考
  remarkError: boolean; // 備考エラーの有無
}

export type { CsvData };
